services:
  postgres:
    image: postgres:latest
    container_name: hotel-database
    ports:
      - 5665:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

volumes:
  db-volume: