services:
  postgres:
    image: postgres:latest
    container_name: hotel-database
    ports:
      - 5665:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hotel

volumes:
  db-volume: